### ISSUE TITLE
Turbine storage and shipping

### ISSUE THREAD

**Issue by petebachant** [UNH-CORE/RM2-tow-tank#93]
We should look to purchase a pre-built wooden crate that is approximately the right size, then design foam inserts to fit all the turbine parts.

**Comment by petebachant** [comment]
I will probably migrate the CAD files over to Onshape for ease of collaboration: https://cad.onshape.com/documents/c34d9735c61a487ba0d327cb/w/39ab4131974849ae904ac64e/e/31ebc8342d6e46fc8452f6d0

**Comment by petebachant** [comment]
Actually, a Pelican Storm 3300 looks like it could be the perfect size.

**Comment by petebachant** [comment]
Looks like the 3300 is a tiny bit too small. Requested CAD models for the 3410.

**Comment by petebachant** [comment]
1770 CAD files are available, though it's a bit thicker and more expensive.

**Comment by petebachant** [comment]
1770 looks like a good fit:

![image](https://cloud.githubusercontent.com/assets/4604869/15193830/d09f30b4-178d-11e6-8ac0-f135388fe50d.png)

**Comment by wosnik** [comment]
It looks like it will fit.

We need some heavy-duty sleeves to protect the hydrofoils. Cloth. Leather, sth.   Old firehose?

**Comment by petebachant** [comment]
Keep in mind the entire case will be filled with foam!

**Comment by wosnik** [comment]
Yes, but the sharp trailing edge can cut through the (segmented) foam pretty easily and hit other metal parts inside the case.
I’ll think of something to rig. We can always just wrap it in fabric. Maybe I’ll fire up the old sewing machine…

**Comment by petebachant** [comment]
A piece of rubber tubing slit down one side on the trailing edges should be fine and quick--no sewing necessary. Everything looks like it will fit nicely inside a 1770:

![image](https://cloud.githubusercontent.com/assets/4604869/15201593/b237a420-17c0-11e6-8531-bc231ff8f8bd.png)

One of the cheaper places I've seen them is WalMart: http://www.walmart.com/ip/Pelican-1770-Long-Case/20923763

**Comment by petebachant** [comment]
It also looks like the foam isn't segmented as small cubes, but full length/width layers, FWIW ("4-piece foam set"):

![image](https://cloud.githubusercontent.com/assets/4604869/15201666/5985b866-17c1-11e6-98c6-a7419200840d.png)

**Comment by wosnik** [comment]
When given an option for foam, make sure it isn’t “pluck foam” – that is the small cube stuff.

**Comment by petebachant** [comment]
All set:

![image](https://cloud.githubusercontent.com/assets/4604869/15522149/779e8162-21de-11e6-80db-1289f37caf75.png)

![image](https://cloud.githubusercontent.com/assets/4604869/15522166/9605cda4-21de-11e6-8ff3-68d25653ad02.png)

I put some polyethylene foam under the blade trailing edges so it wouldn't be able to cut through. Could still put some rubber tubing on them though.
